dbt_ov:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: ov-pipeline
      schema: standardized
      host: dbc-13d0bdd4-38ff.cloud.databricks.com
      http_path: /sql/1.0/warehouses/a47400fd7ea0bda4
      token: dapi10ea9c78d671abc19dc0bb477cbf07c6
      threads: 1