# TODO: Expectation tests, negative/positive test en reference tests
version: 2

models:
  - name: dim_haltes
    description: "Gecleande haltes uit GTFS"
    columns:
      - name: halte_id
        tests:
          - unique
          - not_null
          - no_duplicates
      - name: halte_naam
        tests:
          - not_null
      - name: breedtegraad
        tests:
          - not_null
      - name: lengtegraad
        tests:
          - not_null

  - name: dim_routes
    description: "Gecleande routes uit GTFS"
    columns:
      - name: route_id
        tests:
          - unique
          - not_null
          - no_duplicates
      - name: bureau_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_bureau')
              field: bureau_id
      - name: vervoerstype
        tests:
          - not_null
          - accepted_values:
              values: ['Tram', 'Metro', 'Trein', 'Bus', 'Ferry', 'Onbekend']

  - name: dim_bureau
    description: "Vervoerders uit GTFS"
    columns:
      - name: bureau_id
        tests:
          - unique
          - not_null
          - no_duplicates

  - name: dim_kalender
    description: "Kalender dimensie op basis van calendar_dates"
    columns:
      - name: datum
        tests:
          - unique
          - not_null
      - name: dag_van_de_week
        tests:
          - not_null
      - name: is_weekend
        tests:
          - not_null

  - name: fct_ritten
    description: "Feittabel met ritten gekoppeld aan kalender"
    columns:
      - name: rit_id
        tests:
          - not_null
      - name: route_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_routes')
              field: route_id
      - name: datum
        tests:
          - not_null
          - relationships:
              to: ref('dim_kalender')
              field: datum
