# TODO: Freshness checks, na ingestion time kolom
version: 2

sources:
  - name: raw
    catalog: ov-pipeline
    schema: raw
    tables:
      - name: raw_stops
      - name: raw_routes
      - name: raw_agency
      - name: raw_trips
      - name: raw_calendar_dates
      - name: raw_feestdagen