version: 2

models:
  - name: agg_ritten_per_bureau
    description: "Aantal ritten per vervoerder en vervoerstype"
    columns:
      - name: bureau_naam
        tests:
          - not_null
      - name: vervoerstype
        tests:
          - not_null
      - name: totaal_ritten
        tests:
          - not_null

  - name: agg_ritten_per_route
    description: "Aantal ritten per route"
    columns:
      - name: route_korte_naam
        tests:
          - not_null
      - name: totaal_ritten
        tests:
          - not_null

  - name: agg_rituitval
    description: "Rituitval percentage per vervoerder en vervoerstype"
    columns:
      - name: bureau_naam
        tests:
          - not_null
      - name: uitval_percentage
        tests:
          - not_null
      - name: uitval_percentage
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100