version: 2

models:
  - name: agg_trips_per_agency
    description: "Aantal ritten per vervoerder en type vervoer"
    columns:
      - name: agency_name
        tests:
          - not_null
      - name: route_type
        tests:
          - not_null
      - name: total_trips
        tests:
          - not_null

  - name: agg_trips_per_route
    description: "Aantal ritten per route"
    columns:
      - name: route_short_name
        tests:
          - not_null
      - name: total_trips
        tests:
          - not_null

  - name: agg_rituitval
    description: "Rituitval percentage per vervoerder en type vervoer"
    columns:
      - name: agency_name
        tests:
          - not_null
      - name: uitval_percentage
        tests:
          - not_null
      - name: uitval_percentage
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100