name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# 2 Jobs zodat je kan zien of het SQL of dbt logic is die faalt.
jobs:
  sqlfluff:
    name: SQL Linting
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install sqlfluff sqlfluff-templater-dbt
          pip install dbt-databricks

      - name: dbt deps
        working-directory: dbt
        run: dbt deps

      - name: Run SQLFluff
        run: |
          sqlfluff lint dbt/models/ --dialect sparksql

  dbt_compile:
    name: dbt validate
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dbt
        run: pip install dbt-databricks

      - name: Debug profiles.yml
        run: cat ~/.dbt/profiles.yml

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << EOF
          ov_pipeline:
            target: dev
            outputs:
              dev:
                type: databricks
                catalog: ov-pipeline
                schema: standardized
                host: ${{ secrets.DATABRICKS_HOST }}
                http_path: ${{ secrets.DATABRICKS_HTTP_PATH }}
                token: ${{ secrets.DATABRICKS_TOKEN }}
                threads: 1
          EOF

      - name: dbt deps
        working-directory: dbt
        run: dbt deps

      - name: dbt compile
        working-directory: dbt
        run: dbt compile
      
      - name: dbt test
        working-directory: dbt
        run: dbt test